name: talker_logger
description: Logger core package for talker (advanced error handler and logger package)
version: 1.1.0+1
homepage: https://frezyx.github.io/talker/

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  ansicolor: ^2.0.1

dev_dependencies:
  lint: ^1.8.1
  test: ^1.16.0
